### ISSUE TITLE
Why I cannot run these?

### ISSUE THREAD

**Issue by umbertocerrato** [shysaur/Tricky68k#5]
Hello everyone,

I’m new to 68k asm development.
I just saw these sample programs and I would like them to run on this emulator. I tried but with no results...
What am I missing? (I noticed the missing colons in the labels and the semicolons in place of the asterisks)

Sample files are from: https://www.xrmx.com/solutions/software/68k-fe/samples/index.html

### This is the first one:
```
*       68Sample.x68
*       By Greg Colley
*       Program which adds 3 numbers together and subtracts another.
LOC1    EQU     $2000
LOC2    EQU     $2002
LOC3    EQU     $2004

RESULT  EQU     $2006   Answer Location

        ORG     $1000

*       Main Program
        MOVE.W  LOC1,D0
        ADD.W   LOC2,D0
        ADD.W   LOC3,D0
        SUB.W   #$1F0,D0
        MOVE.W  D0,RESULT
        STOP    #$2700

        END     $1000
```

**Comment by ITzTravelInTime** [comment]
This assembler + emulator uses a different standard for comments and labels, the labels are characters follows by : , so for examample myLabel: [code here] and for comments, they start after ; for example [code here] ;This line of code does something, also programs made in this emulator have to start at address $2000 rather than $1000 your code uses, this assembler also supports code written in non capital characters. And also make sure to end your program with an endless loop, or the emulator will crash at the end of the execution of the code. all this problem came from the fact that those are different assemblers using different standards, so a program to work on this emulator/assembler must be changed.

**Comment by umbertocerrato** [comment]
Hi, thank you! I’ll try it later and see what I get.
Anyway... I’m pretty sure I contacted you via Facebook :)

Best, u

**Comment by shysaur** [comment]
Good answer @ITzTravelInTime, thanks. I did not know about the crash with the `stop` instruction; I will fix that.

In this specific case, the correct version of the program would be:

```
        ORG     $2000

        public  start
start:
;       Main Program
        MOVE.W  LOC1,D0
        ADD.W   LOC2,D0
        ADD.W   LOC3,D0
        SUB.W   #$1F0,D0
        MOVE.W  D0,RESULT
end:
        BRA end

LOC1    ds.w 1
LOC2    ds.w 1
LOC3    ds.w 1
RESULT  ds.w 1
```

However, there is nothing that writes to LOC1, LOC2, and LOC3 (which are memory locations) before the additions are performed. Thus, the value of RESULT at the end will be fairly uninteresting.

**Comment by umbertocerrato** [comment]
Thank you, yeah I notice that.
Yeah, true... maybe it requires those memory locations to have already a value inside(?)

**Comment by umbertocerrato** [comment]
OT: Do you have a Discord Server or something similar like a forum/Skype/... place where to talk?
Anyway... what `ds.w 1` stands for?

**Comment by shysaur** [comment]
This project is way too small to warrant forums or discord servers. It's also not the easiest to use (as the name suggests :wink:)

`ds.w 1`, in simplified terms, defines one word-sized (= 2 bytes) variable.

I cannot teach you all about Motorola 68k assembly language one comment at a time; if you haven't already, search Google for a tutorial you like. As additional references, the "bible" on how the 68k works can be downloaded [here](http://www.freescale.com/files/archives/doc/ref_manual/M68000PRM.pdf), and the manual of the assembler that Tricky68k uses under the hood is [here](http://www.ibaug.de/vasm/doc/vasm.pdf).

Both of these documents won't be easy reads for a beginner, but they contain the answer to every doubt, except for two things:

- in Tricky68k, programs must start at address $2000, which is a side-effect of how the virtual machine in Tricky68k loads programs
- how the teletype works, which is explained in the Hello World example.

Both of these things are unrelated to the CPU itself, but they depend on the devices connected to it: RAM and input/output. Different computers using the same CPU will have different devices which work differently. Thus, only the CPU parts of these tutorials will apply to Tricky68k.

Good Luck!
