### ISSUE TITLE
Nothing appears after Starting the project

### ISSUE THREAD

**Issue by umbertocerrato** [shysaur/Tricky68k#6]
Hello there,

I managed to write some code...
Anyway, also using the Examples stored in the application, pressing the Start button doesn’t show nothing in the Simulator. Is this ok?

I think I should see something different... am I wrong?

**Comment by umbertocerrato** [comment]
![Screenshot](https://user-images.githubusercontent.com/25720138/63060664-25adfa80-bef3-11e9-8855-8248c99df3e8.png)

**Comment by shysaur** [comment]
While a program is in execution, it is normal for the stack/disassembly/registers views are blank. If the program does not use the teletype, that's going to stay blank as well. To "un-blank" them (so to speak) you have to pause execution by clicking the pause button in the toolbar.

I encourage you to read the comments in the example you have run, especially at line 32...

If you want to have some fun, load one of the advanced examples.

P.S.: From the issues you have opened, it seems that you are a beginner at this whole assembly programming thing. If you are just following a tutorial without having any significant programming experience in a high level language it's probably going to be an uphill battle.

**Comment by umbertocerrato** [comment]
Hi,

Thank you.
Yeah I’m learning 68k assembly but I have some basics in computer science. “Things make sense to me”.

Anyway, speaking about the “user experience” of the application... I think it should not stay blank. Would be cool to see the “line” going through the steps in real-time.

Also, that blank Disassembly/Source section is scrollable (for this reason it seems like a bug) and actually if you click inside and then stop the execution, you see you have set breakpoints. I really think it should not behave like this.

Best, u
