### ISSUE TITLE
Having trouble building Tricky68k in Xcode

### ISSUE THREAD

**Issue by rolfmobile99** [shysaur/Tricky68k#9]
Hi Shysaur,
We tried to build your package Tricky68k and get the following error right away:
  Unable to resolve build file:
  XCBCore.BuildFile
  (Named references cannot be resolved...)

We are using Xcode 10.2.
If you happen to have a quick idea what might be going wrong that would be great :-)
-Rolf W (in california)

**Comment by shysaur** [comment]
You either forgot to pull all submodules (do that with `git submodule update --recursive --init`) or you are using an Xcode version that is too old (on Xcode 11.3 it works fine).

**Comment by rolfmobile99** [comment]
Thanks Daniele!! We will try that. -Rolf
